### ISSUE TITLE
ixdat 0.2.0: 'ECMSExporter' object has no attribute 'default_v_list'

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#56]
I was trying to run an old script with the newest ixdat and encountered this error as an `AttributeError` in following line:
`full_data.export("./" + exp_name + ".csv")` where `exp_name` is a string and `full_data` ECMS data imported using the Zilien importer. 
I feel like the `ECMSExporter` should have a `default_v_list`?

**Comment by ScottSoren** [comment]
Thanks for catching this!
This is a bug introduced in #30 and solved in #57.  @AnnaWiniwarter,  if you could chck if this is solved in #57 and if so resolve this issue, that'd be great.
